import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import "../lib/fontawesome";
import { ReduxProvider } from "@/redux/provider";
import Header from "@/components/header/header";
import AuthProvider from "./AuthProvider";
const font = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: [
    "Mua bán sản phẩm",
    "Thời trang",
    "Mua sắm",
    "Thương mại điện tử",
    "Quần áo giá rẻ",
    "Đồ gia dụng",
    "Shop điện tử",
    "Mua bán máy tính",
    "Đồ công nghệ",
    "Mua mọi thứ",
    "web bán hàng",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} antialiased`}>
        <ReduxProvider>
          <AuthProvider>
            <header className="container-xl">
              <Header />
            </header>
            <main className="container">{children}</main>
            <footer></footer>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
